# Generated by Django 3.1 on 2020-09-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liber',
            fields=[
                ('titulli', models.CharField(max_length=255)),
                ('autori', models.CharField(max_length=255)),
                ('cmimi', models.CharField(max_length=255)),
                ('img_src', models.CharField(max_length=255)),
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librat', models.ManyToManyField(to='app.Liber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('emri', models.CharField(max_length=255)),
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('librat', models.ManyToManyField(to='app.Liber')),
            ],
        ),
    ]
